// GENERATED by scripts/unity-export/tripo-face-hlsl.mjs from src/characters/tripo-face.js TRIPO_FACE_GLSL: do not edit.
// The coral-shirt traveller's drawn face (brows, eyes, mouth moved by his expression), in his body's bind space.
#ifndef MEMENTO_TRIPO_FACE_INCLUDED
#define MEMENTO_TRIPO_FACE_INCLUDED

  float4 _TfBrowA;
  float4 _TfBrowB;
  float4 _TfEye;
  float4 _TfMouth;
  float tfCover(float d, float w, float aa) { return 1.0 - smoothstep(w - 0.5 * aa, w + 0.5 * aa, d); }
  float tfOval(float2 p, float2 c, float2 h) { return 1.0 - smoothstep(0.8, 1.0, length((p - c) / h)); }
  // the parabola through three points: its height and slope at x
  float2 tfQuad(float x, float2 a, float2 b, float2 c) {
    float da = (a.x - b.x) * (a.x - c.x), db = (b.x - a.x) * (b.x - c.x), dc = (c.x - a.x) * (c.x - b.x);
    float y = a.y * (x - b.x) * (x - c.x) / da + b.y * (x - a.x) * (x - c.x) / db + c.y * (x - a.x) * (x - b.x) / dc;
    float s = a.y * (2.0 * x - b.x - c.x) / da + b.y * (2.0 * x - a.x - c.x) / db + c.y * (2.0 * x - a.x - b.x) / dc;
    return float2(y, s);
  }
  float3 tripoFace(float3 albedo, float3 b, float aa) {
    if (b.z < 0.035 || b.y < 1.562 || b.y > 1.678 || abs(b.x - (-0.001)) > 0.072) return albedo;
    static const float3 INK = float3(0.075, 0.058, 0.05);
    // 1. cover the paint: the skin round it, where a pixel isn't skin already
    float2 xy = b.xy;
    float er = max(max(tfOval(xy, float2(-0.034, 1.6415), float2(0.0185, 0.0078)), tfOval(xy, float2(0.0315, 1.6415), float2(0.0185, 0.0078))),
      max(max(tfOval(xy, float2(-0.0385, 1.6616), float2(0.0285, 0.0092)), tfOval(xy, float2(0.035, 1.6616), float2(0.0285, 0.0092))), tfOval(xy, float2(-0.0005, 1.5803), float2(0.026, 0.0038))));
    float3 fill = lerp(float3(0.72, 0.505, 0.37), float3(0.684, 0.488, 0.345), 1.0 - smoothstep(0.0, 0.006, abs(b.y - 1.6505)));
    albedo = lerp(albedo, fill, er * smoothstep(0.03, 0.1, distance(albedo, fill)));
    float2 p = float2(b.x - (-0.001), b.y), q = float2(abs(p.x), p.y);
    float side = sign(p.x);
    // 2. the brows: one thick stroke each, square at the inner end, tapering to a point
    float2 I = _TfBrowA.xy, Pk = _TfBrowA.zw, O = _TfBrowB.xy;
    if (q.x > I.x - 0.004 && q.x < O.x + 0.003 && abs(q.y - Pk.y) < 0.016) {
      float x = clamp(q.x, I.x, O.x);
      float2 ys = tfQuad(x, I, Pk, O);
      float t = (x - I.x) / (O.x - I.x);
      float hw = 0.0039 * _TfBrowB.z * lerp(0.9, 1.0, smoothstep(0.0, 0.3, t)) * (1.0 - 0.78 * smoothstep(0.55, 1.0, t));
      float d = length(float2(q.x - x, (q.y - ys.x) / sqrt(1.0 + ys.y * ys.y)));
      if (q.x < I.x) d = max(abs(q.y - ys.x), (I.x - q.x) * 2.2);   // (the inner end cut square, a little rounded)
      albedo = lerp(albedo, INK * 1.15, tfCover(d, max(hw, 0.6 * aa), aa));
    }
    // 3. the eyes: an almond of white, a large dark iris that follows the gaze, the upper lid a heavy lineY
    float u = (q.x - 0.0328) / 0.0163, v = q.y - 1.6415;
    if (abs(u) < 1.25 && abs(v) < 0.011) {
      float s1 = max(1.0 - u * u, 0.0);
      float up0 = 0.0056 * pow(s1, 0.55) + 0.0005 * u;
      float lo = -0.0056 * 0.85 * pow(s1, 0.75) + 0.0004 * u + _TfEye.y * 0.0056 * 0.55 * s1;
      float up = lerp(up0, lo + 0.00015, _TfEye.x);
      float open = step(abs(u), 1.0) * smoothstep(lo - 0.5 * aa, lo + 0.5 * aa, v) * (1.0 - smoothstep(up - 0.5 * aa, up + 0.5 * aa, v));
      float2 ic = float2(0.0328 + side * _TfEye.z, 1.6415 - 0.0004 + _TfEye.w);
      float di = length(q - ic);
      float3 eye = float3(0.88, 0.83, 0.76);
      float iris = 1.0 - smoothstep(0.0066 - 0.5 * aa, 0.0066 + 0.5 * aa, di);
      float3 irisCol = lerp(float3(0.15, 0.095, 0.065), INK, smoothstep(0.0036300000000000004, 0.0056099999999999995, di));
      irisCol = lerp(irisCol, INK * 0.6, 1.0 - smoothstep(0.00264 - 0.5 * aa, 0.00264 + 0.5 * aa, di));
      eye = lerp(eye, irisCol, iris);
      // a catchlight (the same side on both eyes), once there are pixels enough for it
      float hl = 1.0 - smoothstep(0.0011 - 0.5 * aa, 0.0011 + 0.5 * aa, length(float2(p.x - side * ic.x, q.y - ic.y) - float2(-0.0021, 0.0019)));
      eye = lerp(eye, float3(0.97, 0.95, 0.9), hl * (1.0 - smoothstep(0.0006, 0.0011, aa)));
      albedo = lerp(albedo, eye, open);
      // the upper lid: heavier toward the outer corner, a flick past it; it comes down with the blink (a closed eye: one arc)
      float wl = lerp(0.00075, 0.00125, smoothstep(-0.7, 0.9, u)) * smoothstep(-1.06, -0.86, u) * (1.0 - smoothstep(1.0, 1.2, u));
      float uc = clamp(u, -1.0, 1.0);
      float upc = lerp(0.0056 * pow(max(1.0 - uc * uc, 0.0), 0.55) + 0.0005 * uc, lo + 0.00015, _TfEye.x) - max(u - 1.0, 0.0) * 0.012;
      albedo = lerp(albedo, INK, tfCover(abs(v - upc), max(wl, 0.55 * aa * step(0.0001, wl)), aa));
      // the lower lid: a fine lineY under the outer half, darker as a squint or a smile lifts it
      float wlo = 0.00032 * smoothstep(-0.3, 0.2, u) * (1.0 - smoothstep(0.85, 1.0, u));
      albedo = lerp(albedo, INK, (0.3 + 0.5 * _TfEye.y) * tfCover(abs(v - lo), max(wlo, 0.5 * aa * step(0.0001, wlo)), aa));
    }
    // 4. the mouth: one lineY, its corners up or down; open, a dark shape under it (teeth at the top)
    float mw = _TfMouth.x, t = p.x / mw;
    if (abs(t) < 1.35 && abs(p.y - 1.5805) < 0.02) {
      float s2 = max(1.0 - t * t, 0.0);
      float lineY = 1.5805 + _TfMouth.y * t * t - 0.0003 * s2;
      float top = lineY + _TfMouth.w * pow(s2, 0.6), bot = lineY - _TfMouth.z * pow(s2, 0.7);
      float insideM = step(0.0002, _TfMouth.z) * step(abs(t), 1.0) * smoothstep(bot - 0.5 * aa, bot + 0.5 * aa, p.y) * (1.0 - smoothstep(top - 0.5 * aa, top + 0.5 * aa, p.y));
      float3 mc = lerp(float3(0.5, 0.2, 0.17), float3(0.24, 0.08, 0.07), smoothstep(bot, top, p.y));
      mc = lerp(mc, float3(0.92, 0.88, 0.8), step(top - min(0.0022, (top - bot) * 0.3), p.y) * step(0.0035, top - bot) * step(abs(t), 0.62));
      albedo = lerp(albedo, mc, insideM);
      float slope = 2.0 * _TfMouth.y * t / mw;
      float wm = lerp(0.0007, 0.00035, abs(t)) * (1.0 - smoothstep(0.96, 1.06, abs(t)));
      float3 lip = float3(0.24, 0.12, 0.09);
      albedo = lerp(albedo, lip, tfCover(abs(p.y - top) / sqrt(1.0 + slope * slope), max(wm, 0.55 * aa * step(0.0001, wm)), aa));
      // the open mouth's lower edge, finer
      albedo = lerp(albedo, lip, step(0.0006, _TfMouth.z) * tfCover(abs(p.y - bot), max(wm * 0.6, 0.45 * aa * step(0.0001, wm)), aa));
      // the corners: a short tick turned up by a smile, down by a frown
      float ct = abs(t) - 1.05;
      float cy = lineY + _TfMouth.y * (1.0 + 2.0 * ct) * 1.4 - 1.5805;
      float tick = step(abs(ct), 0.1) * tfCover(abs(p.y - 1.5805 - cy), max(0.00035, 0.5 * aa), aa) * smoothstep(0.0003, 0.0012, abs(_TfMouth.y));
      albedo = lerp(albedo, lip, tick * 0.8);
      // the lower lip: a short stroke under the mouth, lowered as it opens
      float ll = 1.0 - smoothstep(0.25, 0.4, abs(p.x) / 0.0195);
      albedo = lerp(albedo, lip, 0.45 * ll * tfCover(abs(p.y - (bot - 0.0047 - 0.0002 * s2)), max(0.0003, 0.45 * aa), aa));
    }
    return albedo;
  }

#endif
